### ISSUE TITLE
Lägg in sida med VMA (Viktigt Meddelande till Allmänheten)

### ISSUE THREAD

**Issue by bonny** [bonny/brottsplatskartan-web#36]
## Todo

- [ ] Bättre lokal-nav
- [x] Om pågående VMA: visa på relevanta platser, t.ex. överst på sidan och som puff(ar) på hela webbplatsen
- [x] Kortare sista led i breadcrumb, blir lite extremt på små skärmar nu
- [x] Skriv blogginlägg
- [x] Twittra
- [x] Facebooka
- [x] Bestäm hur vi ska avgöra om ett VMA är pågående/aktuellt eller inte.
- [x] Titel på enskilda vma är dåliga
- [x] Lägga in breadcrumbs
- [x] Vänta på att ett riktigt VMA kommer så vi kan bekräfta att meddelandet hamnar på sajten
- [x] [Uppgradera MariaDB från 10.1.16 till 10.6.5](https://github.com/dokku/dokku-mariadb#upgrade-service--to-the-specified-versions) för att få stöd för JSON-kolumner.
  - [x] Ta backup
  - [x] kör `dokku mariadb:upgrade mariadb-brottsplatskartan`
  - [x] Nu kör vi 10.6.5-MariaDB-1:10.6.5+maria~focal-log
- [x] Gör egen endppoint som ser lika ut som https://vmaapi.sr.se/api/v2/alerts fast alltid med data, pga det är så sällan data på riktiga URLen så så svårt att testa/implementera
- [x] Bestäm hur (tabellen](#tabellen) ska se ut
- [x] Importera händelser från SR:s API. Lagra orginalhändelsen som JSON i MariaDB.
- [x] Skapa arkiv-sida med rubriker på alla VMA och länkar till varje händelse
- [x] Skapa single-sidor för respektive VMA
- [x] Länka till från ordlistan, från VMA
- [x] Gör FAQ-sida på /vma/vanliga-fragor-om-vma
- [x] Gör OM-sida på /vma/om-vma

## Tabellen

Nåt så här:

**vma_alerts**

| name | type | 
| --- | --- |
| id  | primary key |
| Identifier  | string |
| Sent | date |
| status | string |
| msgType | string |
| references | string |
| incidents | string |
| original_message | json |

## API

- https://www.krisinformation.se/om-krisinformation/for-myndigheter-och-andra-aktorer/oppen-data
- https://vmaapi.sr.se/api/v2/ ~~http://api.sr.se/api/documentation/v2/metoder/vma.html~~

## Andra länkar

- https://sv.m.wikipedia.org/wiki/Viktigt_meddelande_till_allm%C3%A4nheten_(Sverige)

- https://www.krisinformation.se/detta-gor-samhallet/vma-sa-varnas-allmanheten

- https://sverigesradio.se/sida/artikel.aspx?programid=183&artikel=4449074

- https://sverigesradio.se/sida/artikel.aspx?programid=5135&artikel=7008470

- http://api.sr.se/api/documentation/v2/metoder/trafik.html

**Comment by bonny** [comment]
Exempel på svar:

```

<?xml version="1.0" encoding="utf-8"?>
<sr>
  <copyright>Copyright Sveriges Radio 2020. All rights reserved.</copyright>
  <messages>
    <message>
      <id>7502738</id>
      <title>Viktigt meddelande till allmänheten i Löpbacken och Hacksäng i Östersunds kommun</title>
      <description>Det brinner i en industri. Räddningsledaren uppmanar alla i området att stänga dörrar, fönster och ventilation och vid behov gå inomhus. För mer information lyssna på Sveriges Radio P4 Jämtland.</description>
      <date>2020-06-25T11:12:00</date>
      <url>https://sverigesradio.se/sida/artikel.aspx?programid=83&amp;artikel=7502734</url>
    </message>
  </messages>
</sr>
```

**Comment by bonny** [comment]
Exempel på svar från http://api.krisinformation.se/v1/feed

**Comment by bonny** [comment]
Ett till exempel:

```json
{
  "copyright": "Copyright Sveriges Radio 2021. All rights reserved.",
  "messages": [
    {
      "id": 7755226,
      "title": "VMA i Landskrona i Skåne län",
      "description": "• Det brinner i ett fartyg med skrot i Landskrona hamn. Räddningsledaren uppmanar alla i området där det finns rök att gå inomhus och stänga dörrar, fönster och ventilation. För mer information lyssna på Sveriges Radio P4 Kristianstad eller P4 Malmöhus.",
      "date": "/Date(1622466840000+0200)/",
      "url": "https://sverigesradio.se/artikel/7755223"
    }
  ]
}
```

**Comment by bonny** [comment]
Det verkar som att SR har ett nyare API (som inte det skrivs något om?). Hittade tack vare Google denna:

https://vmaapi.sr.se/api/v2/

Efter lite mer Googlade så hittade jag https://groups.google.com/g/sr-api/c/QBz_tfRPgxQ?pli=1 och där säger SR att:

> Vi behöver uppdatera sidan för att förtydliga att det finns två olika VMA-api.
> Det som beskrivs på api.sr.se är det som innehåller de VMA-puffar som tar vägen över vårat CMS, medans det som låg på vma.sr.se är de 'riktiga' VMA-meddelandena.
> 
> Den nya adressen för vma.sr.se är https://vmaapi.sr.se/api/v2 och det finns ett testapi på https://vmaapi.sr.se/testapi/v2

https://groups.google.com/g/sr-api/c/QBz_tfRPgxQ?pli=1

**Comment by bonny** [comment]
Exempel med "nya" apiet från SR:

https://vmaapi.sr.se/api/v2/alerts

```json
{
  "timestamp": "2021-05-31T13:01:25+02:00",
  "alerts": [
    {
      "identifier": "SRCAP20210531150110I",
      "sender": "https://vmaapi.sr.se/api/v2",
      "sent": "2021-05-31T15:01:10+02:00",
      "status": "Actual",
      "msgType": "Alert",
      "scope": "Public",
      "references": null,
      "incidents": "SRVMA20210531150110I",
      "info": [
        {
          "language": "sv-SE",
          "category": "Safety",
          "event": "Viktigt meddelande till allmänheten (VMA)",
          "urgency": "Immediate",
          "severity": "Severe",
          "certainty": "Observed",
          "senderName": "Sveriges Radio",
          "description": "Viktigt meddelande till allmänheten i Landskrona i Skåne län.\r\n\r\nDet brinner i ett fartyg med skrot i Landskrona hamn. \r\n\r\nRäddningsledaren uppmanar alla i området där det finns rök att gå inomhus och stänga dörrar, fönster och ventilation.\r\n\r\nFör mer information lyssna på Sveriges Radio P4 Kristianstad eller P4 Malmöhus.",
          "web": "https://sverigesradio.se/sida/artikel.aspx?programid=183&amp;artikel=4489542",
          "area": [
            {
              "areaDesc": "Skåne län",
              "geocode": [
                {
                  "valueName": "Län",
                  "value": "12"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

```
