### ISSUE TITLE
Ta bort AMP, använd HTML

### ISSUE THREAD

**Issue by bonny** [bonny/brottsplatskartan-web#55]
[Google Funding Choices](https://fundingchoices.google.com/) stöder inte AMP och vi behöver få GFC att fungera så vi kan visa annonser för att betala serverkostnaderna. 

**Todo**

- [x] accordion och andra custom elements
- [x] Testa att det fungerar att posta plats + media
- [x] ads
- [x] consent - måste få adsense på plats först?
- [ ] Minska ner sidhuvud vid scroll (eller bara göra den alltid mindre?)
- [x] GA
- [x] Ta bort amp-skripten
- [x] <img> som hade layout=responsive ska ta upp hela containern
- [x] Stats-pixel
- [x] lazy load image
